[package]
name = "tsgateway"
version = "0.1.0"
edition = "2024"

[lib]
name = "tsgateway"
crate-type = ["cdylib"]

[dependencies]
tree-sitter = "0.24"
tree-sitter-rust = "0.23"
tree-sitter-c = "0.23"
tree-sitter-python = "0.23"
tree-sitter-odin = "1.3.0"
streaming-iterator = "0.1.9"
